### ISSUE TITLE
Cannot use in Android because of awt classes

### ISSUE THREAD

**Issue by royale1223** [vandeseer/easytable#76] opened 2020-03-05 09:25 UTC
Since this library uses `java.awt.*` classes, which isn't a part of Android, it's impossible to use it inside an Android Project. Please consider removing dependency on awt classes and making the library Android complaint.

**Comment by vandeseer** [comment] 2020-03-10 13:07
The problem is that the underlying library (which is Apache PDFBox) uses those dependencies. So this is unfortunately nothing that can be fixed within easytable.

**Closed** 2020-03-11 19:15 UTC

**Comment by krprashant94** [comment] 2021-01-13 09:05
Please make an alternate by using  [PdfBox-Android](https://github.com/TomRoush/PdfBox-Android) or [VivyTeam - pdfbox-android ](https://github.com/VivyTeam/pdfbox-android)
