### ISSUE TITLE
Pagination not working properly for multiple tables with multiple pages

### ISSUE THREAD

**Issue by SagarKadu** [vandeseer/easytable#44] opened 2019-08-08 06:05 UTC
How to draw multiple tables paginated across different pages using current lib..i.e. new table should be drawn next to existing one in paginated fashion

**Comment by vandeseer** [comment] 2019-08-08 06:59
I will have a look to come up with a simple example as soon as I find some time for it. Maybe you can already share what you tried so far.

**Comment by SagarKadu** [comment] 2019-08-08 07:30
I tried ExcelLikeExampleTest with 2 tables..as long as 2 tables have data within 1 page it works fine but if data grows over 1 page for any one of the table it breaks..I tried combining example of TableOverServeralPages with ExcelLikeExampleTest but it doesn't work properly

**Comment by vandeseer** [comment] 2019-08-11 15:55
After having a closer look I think the easiest solution is to adapt the `TableDrawer` class a bit in the library. The idea is to add an additional member that stores the `y` value at the end, i.e. when drawing the table is finished.

**Comment by vandeseer** [comment] 2019-09-29 08:12
The issue is fixed with release 0.5.1. One can now draw several multipage tables on the same document.

**Closed by vandeseer** 2019-09-29 08:12 UTC
Labels: help wanted, question

**Comment by arunmurukesh** [comment] 2020-01-16 05:34
Unable to determine the Y coordinate for the second multipage table within same document, Table is being drawn with more space.

Please share me a working example if anyone has

**Comment by vandeseer** [comment] 2020-02-01 17:38
Hey @arunmurukesh, please have a look at https://github.com/vandeseer/easytable/issues/59 – there is an example on how to do it.
