### ISSUE TITLE
Enabling WordBreak on Tables causes a Stackoverflow on cells with only a single character

### ISSUE THREAD

**Issue by TheSilentHorizon** [vandeseer/easytable#20] opened 2018-11-19 11:00 UTC
When you have single character CellTexts WordBreak breaks (haha.) . 

How to reproduce:

Create a cell with only one single CellText. Causes this StackoverflowError:

```
Exception in thread "JavaFX Application Thread" java.lang.StackOverflowError
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.apache.pdfbox.pdmodel.font.PDType1Font.encode(PDType1Font.java:412)
	at org.apache.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:324)
	at org.apache.pdfbox.pdmodel.font.PDFont.getStringWidth(PDFont.java:353)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.getStringWidth(PdfUtil.java:27)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.isLineFine(PdfUtil.java:120)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:65)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:72)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:72)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:72)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:72)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:72)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:72)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:72)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:72)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:72)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:72)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:72)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.wrapLine(PdfUtil.java:72)
	at org.vandeseer.pdfbox.easytable.util.PdfUtil.splitBySize(PdfUtil.java:87)
```

Quick fix **is to add an empty character to the given CellText.** Looks a bit off when entered or right aligned but is still better then nothing. Will next week look into this issue myself if it isnt fixed until then, but due to the lack of time im just writing an issue for now.

**Comment by vandeseer** [comment] 2018-11-19 14:38
Thanks for pointing that out @TheSilentHorizon! 

Actually I made a TODO note already in one of the tests because I stumbled across that as well: https://github.com/vandeseer/easytable/blob/develop/src/test/java/org/vandeseer/easytable/structure/cell/CellTextTest.java

Unfortunately I didn't yet fix it though ... :D
But it's on my list now (again). 

PS: Also note that currently it's not possible to have line breaks for new line characters in the word break feature. That's a second thing I would like to work on but didn't yet find the time.

**Comment by vandeseer** [comment] 2018-11-19 19:36
Could you check out the latest commit on `develop`? It should be fixed. If everything's alright I will merge to master soon, because some other things are also ready :)

**Comment by vandeseer** [comment] 2018-11-20 20:34
I merged it to master now after creating a small test PDF which looked fine. Just reopen the issue in case you don't think it's fine ;)

**Comment by TheSilentHorizon** [comment] 2018-11-20 21:38
Latest build turned my single char elements invisible. Have you tried testing it with digits?

**Comment by vandeseer** [comment] 2018-11-21 08:33
Sorry to hear that. Could you post your code so that I could reproduce it? Thanks already :)

**Comment by TheSilentHorizon** [comment] 2018-11-21 08:39
**How it is**

![image](https://user-images.githubusercontent.com/29006783/48828796-fb1e7f00-ed70-11e8-822f-36919d4d04d4.png)

**How it should be**

![image](https://user-images.githubusercontent.com/29006783/48828865-25703c80-ed71-11e8-82ce-7b1d9107463c.png)


The line of code responsible for the amount of products being added to the row:

`                .add(CellText.builder().text(line.getAmount() + " ").horizontalAlignment(RIGHT).borderWidth(1).build())`

**Comment by vandeseer** [comment] 2018-11-21 08:55
Actually I think your table is a pretty nice example of what the library could do for you – if it only worked, dammit 😆 

Would you mind creating the code for that table in this folder https://github.com/vandeseer/easytable/blob/develop/src/test/java/org/vandeseer/integrationtest in a file of its own and pull request it to the `develop` branch? 

That would make it easier for me to trace the issue and afterwards we could add this table as a further example what shiny tables can be produced 😉

**Comment by vandeseer** [comment] 2018-11-21 21:12
I quickly hacked together a table like the one you posted above. You can find the code here: 
https://github.com/vandeseer/easytable/blob/develop/src/test/java/org/vandeseer/integrationtest/WordWrappingTest.java#L42

The output looks like this: 

![example3](https://user-images.githubusercontent.com/9912755/48868521-22f5fd00-edda-11e8-99f9-bc472127c930.png)

So could it be the case that you have an extra column that is too narrow and you place the numbers in there? Again: If you could paste the full code for a minimal non-working example that would be very helpful :) 

Best, 
Stefan

**Comment by TheSilentHorizon** [comment] 2018-11-22 08:13
Will look onto it on the weekend, currently busy ;)

**Comment by TheRealSourceSeeker** [comment] 2018-12-14 12:05
Had the same issue when using the first blue table shown under "Example". To reproduce, just open "org.vandeseer.integrationtest.ExcelLikeExampleText.java" and replace for example `"Gin"` with `"Kr."` or `"K."` (in the 2D array `final Object[][] data = {`). "Kr." becomes "K-" + NewLine + "r.", while "K." isn't shown at all. To fix this, I compared the `maxWidth` values of the `private void drawCellText` in "org.vandeseer.easytable.TableDrawer.java" which returns 10.223999 for "Kr." or 7.5599995 for "K."with the values of the `private static float getWidthOfStringWithoutNewlines` in "org.vandeseer.easytable.util.PdfUtil.java" which returns 10.224 for "Kr." or 7.56 for "K.". So there seems to be a rounding problem. To fix it, i added the following 1 line: `maxWidth = (float) Math.round(maxWidth *1000) /1000;` to "org.vandeseer.easytable.TableDrawer.java" to the `private void drawCellText` between lines `float maxWidth = cell.getWidthOfTextAndHorizontalPadding() - (cell.getPaddingLeft() + cell.getPaddingRight());` and `if (table.isWordBreak()) {`. After this, compared values are both 10.224 for "Kr." or 7.56 for "K.". This results in expected behaviour - "Kr." is shown in 1 line and "K." isn't hidden. :-)

**Comment by vandeseer** [comment] 2018-12-14 16:19
Thanks a lot for your comment @TheRealSourceSeeker! 👍 :) 
I will definitely have a look.

**Comment by vandeseer** [comment] 2019-01-01 20:48
It should be fine now – if you encounter any issues, please let me know and open a issue again. Thanks.

**Closed by vandeseer** 2019-01-01 20:48 UTC

**Comment by ssatya21** [comment] 2021-11-02 02:07
> I had a look now and it seems the issue is indeed the usage of `float` and in particular the last line of the method `getWidthOfTextAndHorizontalPadding()`, which is:
> 
> ```
> return textWidth + getHorizontalPadding();
> ```
> 
> The `textWidth` is calculated as 7.56, but adding the padding (which is 8.0) does not result in 15.56, but 15.559999. Funnily enough the padding is subtracted later anyway, so I started by a small refactoring (see: [db6c347](https://github.com/vandeseer/easytable/commit/db6c347eca92261d17a2cc47d89d520796974d9a)).
> 
> This already solved the issue at least for the case you reported @TheRealSourceSeeker. Not sure though about the case of @TheSilentHorizon (could you try again with the latest develop branch?).
> 
> It may still make sense to do the comparison differently in the `isLineFine(...)` method in the `PdfUtil` class to take into account rounding issues the way you described it above. I will most probably add this as well shortly.
> 
> Again thanks a lot for your precise analysis @TheRealSourceSeeker! 👍

Is this issue fixed in latest version

**Comment by vandeseer** [comment] 2021-11-02 10:51
Hi @ssatya21, 

the problem itself should already be fixed. 
Is it possible to share the code that breaks?

Thanks,
Stefan

**Comment by ssatya21** [comment] 2021-11-02 11:55
I can't paste the code but the problem I see is- when the text is split by
size, a hyphen is getting appended and I don't want to append it
Is there a way to do that
For ex: maturity date is displayed as
Matu-
Rity
Date
Inside the textcell

This is the code from PdfUtil.splitbysize method

final String fittedNewLine = line.substring(0, i) + "-"
