### ISSUE TITLE
Border on table is not applied

### ISSUE THREAD

**Issue by paal1** [vandeseer/easytable#22] opened 2018-11-23 11:12 UTC
Hello,
I try to put different border and color and is never show.
Great project.
Thanks

**Comment by vandeseer** [comment] 2018-11-23 15:13
Hey @paal1, could you provide your code and describe a little better what exactly is not working? 

Also have a look at the examples here: https://github.com/vandeseer/easytable/tree/master/src/test/java/org/vandeseer/integrationtest

It should hopefully cover what you are searching for ;)

**Comment by paal1** [comment] 2018-11-23 16:18
Should draw a border around the table.

Example:
TableBuilder table;
table.setFont(HELVETICA)
	.setBorderWidth(1)
	.setBorderColor(Color.Black);

**Comment by vandeseer** [comment] 2018-11-24 09:45
Please have a look at this file for instance: https://github.com/vandeseer/easytable/blob/master/src/test/java/org/vandeseer/integrationtest/WordWrappingTest.java

So your code should look like this: 

    final Table.TableBuilder tableBuilder = Table.builder()
                .addColumnsOfWidth(8, 8, 8)
                .fontSize(12)
                .font(HELVETICA)
                .borderColor(Color.RED)
                .wordBreak(true);

        tableBuilder.addRow(Row.builder()
                .add(CellText.builder().text("a").borderWidth(1).padding(0f).horizontalAlignment(CENTER).build())
                .add(CellText.builder().text("B").borderWidth(1).padding(0f).build())
                .add(CellText.builder().text("#").borderWidth(1).padding(0f).build())
                .build());

        tableBuilder.addRow(Row.builder()
                .add(CellText.builder().text("c").borderWidth(1).padding(0f).horizontalAlignment(RIGHT).build())
                .add(CellText.builder().text("D").borderWidth(1).padding(0f).build())
                .add(CellText.builder().text("g").borderWidth(1).padding(0f).build())
                .build());

      final PDDocument document = new PDDocument();
      final PDPage page = new PDPage(PDRectangle.A4);
      document.addPage(page);

      try (final PDPageContentStream contentStream = new PDPageContentStream(document, page)) {

          TableDrawer.builder(tableBuilder.build())
                  .contentStream(contentStream)
                  .table(table)
                  .startX(50)
                  .startY(page.getMediaBox().getHeight() - 50)
                  .build()
                  .draw();

      }

      document.save("outputFileName.pdf");
      document.close();

**Comment by paal1** [comment] 2018-11-24 20:34
I thought the method was to create a border around the table.
Why the method setBorderWidth in the table if is not used?

**Comment by vandeseer** [comment] 2018-11-24 22:47
Which version are you using? There shouldn't be any publicly accessible "setBorderWidth" method on the table builder (and neither on the table) anymore in the latest version.

**Comment by paal1** [comment] 2018-11-24 22:53
I think is from a month ago.

**Comment by vandeseer** [comment] 2018-11-27 16:03
I will close the issue now since it's possible to add a border around a table, i.e. it's not a bug.

**Closed by vandeseer** 2018-11-27 16:03 UTC
